---
language: go
go:
 - "1.13.x"

git:
 depth: 1

branches:
 only:
  - master

notifications:
 slack: tek-oso:tBStikUyvah8EOPb8QY7VWvS

before_install:
 - GO111MODULE=on GOPROXY=direct go get github.com/nlynchjo/liche

script:
 - liche -v -t 60 -r .
