name: md link-check
on:
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out HEAD commit of a PR into the Go module directory  
      uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.after }}

    - name: md linkcheck
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: on
      run: |
        go get -u github.com/raviqqe/liche
        $GOPATH/bin/liche -v -t 60 -x forum -r ${{ runner.workspace }}/Programmatic-Control-Examples
