name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: md linkcheck
      run: |
        GO11MODULES=on go get -u go get -u github.com/raviqqe/liche@0.1.1
        liche -v -t 60 -r Programmatic-Control-Examples 
